/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import entidades.*;
import java.awt.Point;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import jdk.nashorn.internal.scripts.JO;

/**
 *
 * @author user
 */
public class jFBatalla extends javax.swing.JFrame {
    private URL url;
    private String nombreB ;
    private String nombreRIval;
    private String entrenador;
    private int vidaM;
    private int vidaR;
    private int cant1 = 3;
    private int cant2 = 3;
    
    //Instanciando...
    Charizard charizard = new Charizard(nombreB);
    Frogadier frogadier = new Frogadier(nombreB);
    Gogoat gogoat = new Gogoat(nombreB);
    
    Persona p1 = new Persona("ASH KETCHUM", "MASCULINO");
     
     
    public jFBatalla() {
        initComponents();
        this.setLocationRelativeTo(null);

        
        Imagen();
        NombreSexo();
                
        
        jLabel12.setText(p1.getNombre());
        jLabel13.setText(p1.getSexo());
        
        MostrarPokemon();
        cambiarNPokemon();
        mostrarEstado();
        
        String cad ="Cant. Poción: " + cant1 + "";
        String cad1 = "Cant. Poción: " +cant2 + "";
        
        jLabel19.setText(cad);
        jLabel20.setText(cad1);
    }

    public void Imagen(){
        if (jFEntrenador.jRadioButton1.isSelected()){
            jLabel1.setVisible(true);
            jLabel2.setVisible(false);
        }
        else if (jFEntrenador.jRadioButton2.isSelected()){
            jLabel1.setVisible(false);
            jLabel2.setVisible(true);
        }
    }
    public void NombreSexo(){
        entrenador = jFEntrenador.nombre;
        jLabel8.setText(jFEntrenador.nombre);
        jLabel9.setText(jFEntrenador.sexo);
        
        
    }
    
    public void MostrarPokemon(){
        if (jFPokemon.jRadioButton1.isSelected()){
            url = this.getClass().getResource("/Imagenes/Charizard.gif");
            ImageIcon icon = new ImageIcon(url);
            jLabel4.setIcon(icon);
            
            url = this.getClass().getResource("/Imagenes/Frogadier.gif");
            ImageIcon icon2 = new ImageIcon(url);
            jLabel5.setIcon(icon2);
        }
        else if(jFPokemon.jRadioButton2.isSelected()){
            url = this.getClass().getResource("/Imagenes/Gogoat.gif");
            ImageIcon icon = new ImageIcon(url);
            jLabel4.setIcon(icon);
            
            url = this.getClass().getResource("/Imagenes/Charizard.gif");
            ImageIcon icon2 = new ImageIcon(url);
            jLabel5.setIcon(icon2);
        }
        else if(jFPokemon.jRadioButton3.isSelected()){
            url = this.getClass().getResource("/Imagenes/Frogadier.gif");
            ImageIcon icon = new ImageIcon(url);
            jLabel4.setIcon(icon);
            
            url = this.getClass().getResource("/Imagenes/Gogoat.gif");
            ImageIcon icon2 = new ImageIcon(url);
            jLabel5.setIcon(icon2);
        }
    }
    public void cambiarNPokemon(){
        
        nombreRIval = jFPokemon.nombreR;
        
        
        if(jFCambiarNombrePokemon.jRadioButton2.isSelected()){
            nombreB = jFPokemon.nombre;
        }
        else if(jFCambiarNombrePokemon.jRadioButton1.isSelected()){
            nombreB=jFCambiarNombrePokemon.Cnombre;
            
        }
        jLabel15.setText(nombreRIval);
        jLabel14.setText(nombreB);
    }
    public void mostrarEstado(){
        if (jFPokemon.jRadioButton1.isSelected()){
            charizard.setNombre(nombreB);
            frogadier.setNombre(nombreRIval);
            jLabel17.setText(charizard.MostrarEstado());
            jLabel18.setText(frogadier.MostrarEstado());
        }
        else if (jFPokemon.jRadioButton2.isSelected()){
            gogoat.setNombre(nombreB);
            charizard.setNombre(nombreRIval);
            
            jLabel17.setText(gogoat.MostrarEstado());
            jLabel18.setText(charizard.MostrarEstado());
        }
        else if (jFPokemon.jRadioButton3.isSelected()){
            frogadier.setNombre(nombreB);
            gogoat.setNombre(nombreRIval); 
            jLabel17.setText(frogadier.MostrarEstado());
            jLabel18.setText(gogoat.MostrarEstado());
        }
    }
    
   /**
     * 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EntrenadorVaron.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 31, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("NOMBRE:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("SEXO:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("NOMBRE/ENTRENADOR");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 170, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("SEXO");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EntrenadoraMujer.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 51, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Entrenador_varon.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 51, 143, 343));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("NOMBRE: ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 410, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setText("NOMBRE");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 410, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setText("SEXO");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 430, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("SEXO:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 430, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 255, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("ATACAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, 100, 30));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 470, 1010, 190));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Charizard.gif"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 176, 190, 188));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Frogadier.gif"))); // NOI18N
        jLabel4.setToolTipText("");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, -1, 174));

        jLabel14.setFont(new java.awt.Font("Tiger Expert", 1, 14)); // NOI18N
        jLabel14.setText("NOMBRE");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tiger Expert", 1, 14)); // NOI18N
        jLabel15.setText("NOMBRE");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 180, -1, -1));

        jButton2.setFont(new java.awt.Font("Tiger Expert", 0, 12)); // NOI18N
        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 10, -1, -1));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel17.setText("VIDA/HP");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, -1, -1));

        jLabel18.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel18.setText("VIDA/HP");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 370, 210, -1));

        jLabel19.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel19.setText("Cantidad de Pociones");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, -1, -1));

        jLabel20.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel20.setText("Cantidad de Pociones");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 390, -1, -1));

        jButton3.setBackground(new java.awt.Color(255, 255, 51));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("CURAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 420, -1, 30));

        jButton4.setBackground(new java.awt.Color(255, 0, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("RENDIRSE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 420, -1, 30));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Estado pokemon.png"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 780));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
        int at = (int)(Math.random()*100);
        
        if (at<=75){

            if (jFPokemon.jRadioButton1.isSelected()){

                charizard.setDano((int)(Math.random()*5+5));
                frogadier.setDano((int)(Math.random()*7+5));

                frogadier.setEvasion(20);
                frogadier.setProbabilidad(20);
                frogadier.setCritico(3);

                String resultado = charizard.atacar(frogadier);
                String resultado2 = frogadier.atacar(charizard);

                jTextArea1.append(entrenador + ">>>  " + resultado + "\n" );
                jTextArea1.append(p1.getNombre() + ">>>  " +resultado2 + "\n\n");


                jLabel17.setText(charizard.MostrarEstado());
                jLabel18.setText(frogadier.MostrarEstado());
                
            }
            if (jFPokemon.jRadioButton2.isSelected()){

                gogoat.setDano((int)(Math.random()*5+5));
                charizard.setDano((int)(Math.random()*7+5));

                charizard.setEvasion(20);
                charizard.setProbabilidad(20);
                charizard.setCritico(3);

                String resultado = gogoat.atacar(charizard);
                String resultado2 = charizard.atacar(gogoat);

                jTextArea1.append(entrenador + ">>>  " + resultado + "\n" );
                jTextArea1.append(p1.getNombre() + ">>>  " +resultado2 + "\n\n");


                jLabel17.setText(gogoat.MostrarEstado());
                jLabel18.setText(charizard.MostrarEstado());
                
            }
            if (jFPokemon.jRadioButton3.isSelected()){

                frogadier.setDano((int)(Math.random()*5+5));
                gogoat.setDano((int)(Math.random()*7+5));

                gogoat.setEvasion(20);
                gogoat.setProbabilidad(20);
                gogoat.setCritico(3);

                String resultado = frogadier.atacar(gogoat);
                String resultado2 = gogoat.atacar(frogadier);

                jTextArea1.append(entrenador + ">>>  " + resultado + "\n" );
                jTextArea1.append(p1.getNombre() + ">>>  " +resultado2 + "\n\n");


                jLabel17.setText(frogadier.MostrarEstado());
                jLabel18.setText(gogoat.MostrarEstado());
                
            }
        }
        
        //Para usar pocion del retador-------------
        else{
            if (jFPokemon.jRadioButton1.isSelected()){
                
                charizard.setDano((int)(Math.random()*5+5));
                frogadier.setDano((int)(Math.random()*7+5));
                frogadier.setEvasion(20);
                frogadier.setProbabilidad(20);
                frogadier.setCritico(3);

                if (cant2>0){
                    String resultado = charizard.atacar(frogadier);
                    String resultado2 = frogadier.usarPocion(frogadier);

                    jTextArea1.append(entrenador + ">>>  " + resultado + "\n" );
                    jTextArea1.append(p1.getNombre() + ">>>  " +resultado2 + "\n\n");


                    jLabel17.setText(charizard.MostrarEstado());
                    jLabel18.setText(frogadier.MostrarEstado());
                    
                    cant2 = cant2 -1;
                }
                else{
                    String resultado = charizard.atacar(frogadier);
                    String resultado2 = frogadier.atacar(charizard);

                    jTextArea1.append(entrenador + ">>>  " + resultado + "\n" );
                    jTextArea1.append(p1.getNombre() + ">>>  " +resultado2 + "\n\n");


                    jLabel17.setText(charizard.MostrarEstado());
                    jLabel18.setText(frogadier.MostrarEstado());
                }
            }
            if (jFPokemon.jRadioButton2.isSelected()){
                
                gogoat.setDano((int)(Math.random()*5+5));
                
                //cambiamos atributos;
                charizard.setDano((int)(Math.random()*7+5));
                charizard.setEvasion(20);
                charizard.setProbabilidad(20);
                charizard.setCritico(3);

                if (cant2>0){
                    String resultado = gogoat.atacar(charizard);
                    String resultado2 = charizard.usarPocion(charizard);

                    jTextArea1.append(entrenador + ">>>  " + resultado + "\n" );
                    jTextArea1.append(p1.getNombre() + ">>>  " +resultado2 + "\n\n");


                    jLabel17.setText(gogoat.MostrarEstado());
                    jLabel18.setText(charizard.MostrarEstado());
                    
                    cant2 = cant2 -1;
                }
                else{
                    String resultado = gogoat.atacar(charizard);
                    String resultado2 = charizard.atacar(gogoat);

                    jTextArea1.append(entrenador + ">>>  " + resultado + "\n" );
                    jTextArea1.append(p1.getNombre() + ">>>  " +resultado2 + "\n\n");


                    jLabel17.setText(gogoat.MostrarEstado());
                    jLabel18.setText(charizard.MostrarEstado());
                }
            }
            
            
            if (jFPokemon.jRadioButton3.isSelected()){
                
                frogadier.setDano((int)(Math.random()*5+5));
                
                //cambiamos atributos;
                gogoat.setDano((int)(Math.random()*7+5));
                gogoat.setEvasion(20);
                gogoat.setProbabilidad(20);
                gogoat.setCritico(3);

                if (cant2>0){
                    String resultado = frogadier.atacar(gogoat);
                    String resultado2 = gogoat.usarPocion(gogoat);

                    jTextArea1.append(entrenador + ">>>  " + resultado + "\n" );
                    jTextArea1.append(p1.getNombre() + ">>>  " +resultado2 + "\n\n");


                    jLabel17.setText(frogadier.MostrarEstado());
                    jLabel18.setText(gogoat.MostrarEstado());
                    
                    cant2 = cant2 -1;
                }
                else{
                    String resultado = frogadier.atacar(gogoat);
                    String resultado2 = gogoat.atacar(frogadier);

                    jTextArea1.append(entrenador + ">>>  " + resultado + "\n" );
                    jTextArea1.append(p1.getNombre() + ">>>  " +resultado2 + "\n\n");


                    jLabel17.setText(frogadier.MostrarEstado());
                    jLabel18.setText(gogoat.MostrarEstado());
                }
            }
            
        }
        
        //
       
        //------------------------------------
        if (jFPokemon.jRadioButton1.isSelected()){
            jLabel17.setText(charizard.MostrarEstado());
            jLabel18.setText(frogadier.MostrarEstado());

            
            String cad1 = "Cant. Poción: " + cant2 + "";

            jLabel20.setText(cad1);
        }
        if (jFPokemon.jRadioButton2.isSelected()){
            jLabel17.setText(gogoat.MostrarEstado());
            jLabel18.setText(charizard.MostrarEstado());

            
            String cad1 = "Cant. Poción: " + cant2 + "";

            jLabel20.setText(cad1);
        }
        if (jFPokemon.jRadioButton3.isSelected()){
            jLabel17.setText(frogadier.MostrarEstado());
            jLabel18.setText(gogoat.MostrarEstado());

            
            String cad1 = "Cant. Poción: " + cant2 + "";

            jLabel20.setText(cad1);
        }
        
      
        
        analizarEstado();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void analizarEstado(){
        
        if (jFPokemon.jRadioButton1.isSelected()){
            
            if(charizard.getVida() == 0 & frogadier.getVida() == 0){
                jTextArea1.append(("\tEsto es un empate"));
                jButton1.setEnabled(false);
                jButton3.setEnabled(false);
                jButton4.setEnabled(false);
            }
            else if (charizard.getVida() == 0) {
                jTextArea1.append("\n" +charizard.getNombre()
                        + " Ya no puede continuar. "
                        + frogadier.getNombre() + " gana.");
            
                jButton1.setEnabled(false);
                jButton3.setEnabled(false);
                jButton4.setEnabled(false);
            }
        
            else if (frogadier.getVida() == 0) {
                jTextArea1.append("\n"+frogadier.getNombre()
                        + " Ya no puede continuar. "
                        +    charizard.getNombre() + " gana.");
            
                jButton1.setEnabled(false);
                jButton3.setEnabled(false);
                jButton4.setEnabled(false);
            }
            
        }
        if (jFPokemon.jRadioButton2.isSelected()){
            
            if(gogoat.getVida() == 0 & charizard.getVida() == 0){
                jTextArea1.append(("\tEsto es un empate"));
            }
            else if (gogoat.getVida() == 0) {
                jTextArea1.append("\n" +gogoat.getNombre()
                        + " Ya no puede continuar. "
                        + charizard.getNombre() + " gana.");
            
                jButton1.setEnabled(false);
                jButton3.setEnabled(false);
                jButton4.setEnabled(false);
            }
        
            else if (charizard.getVida() == 0) {
                jTextArea1.append("\n"+charizard.getNombre()
                        + " Ya no puede continuar. "
                        +    gogoat.getNombre() + " gana.");
            
                jButton1.setEnabled(false);
                jButton3.setEnabled(false);
                jButton4.setEnabled(false);
            }
            
        }
        if (jFPokemon.jRadioButton3.isSelected()){
            
            if(frogadier.getVida() == 0 & gogoat.getVida() == 0){
                jTextArea1.append(("\tEsto es un empate"));
            }
            else if (frogadier.getVida() == 0) {
                jTextArea1.append("\n" +frogadier.getNombre()
                        + " Ya no puede continuar. "
                        + gogoat.getNombre() + " gana.");
            
                jButton1.setEnabled(false);
                jButton3.setEnabled(false);
                jButton4.setEnabled(false);
            }
        
            else if (gogoat.getVida() == 0) {
                jTextArea1.append("\n"+gogoat.getNombre()
                        + " Ya no puede continuar. "
                        +    frogadier.getNombre() + " gana.");
            
                jButton1.setEnabled(false);
                jButton3.setEnabled(false);
                jButton4.setEnabled(false);
            }
        }
        
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (jFPokemon.jRadioButton1.isSelected()){

            frogadier.setDano((int)(Math.random()*7+5));

            frogadier.setEvasion(20);
            frogadier.setProbabilidad(20);
            frogadier.setCritico(3);
            
            String resultado = "";
            String resultado2 = "";
           
            if(cant1>0){
                resultado = charizard.usarPocion(charizard);
                resultado2 = frogadier.atacar(charizard);
            }
            jTextArea1.append(entrenador + ">>>  " + resultado + "\n" );
            jTextArea1.append(p1.getNombre() + ">>>  " +resultado2 + "\n\n");

            jLabel17.setText(charizard.MostrarEstado());
            
            
            cant1 = cant1 -1;
            String n1 = cant1 + "";
            jLabel19.setText("Cant. Poción: " +n1);
            if (cant1==0){
                jButton3.setEnabled(false);
            }
            }
        
        
        
        if (jFPokemon.jRadioButton2.isSelected()){

            charizard.setDano((int)(Math.random()*7+5));

            charizard.setEvasion(20);
            charizard.setProbabilidad(20);
            charizard.setCritico(3);
            
            String resultado = "";
            String resultado2 = "";
           
            if(cant1>0){
                resultado = gogoat.usarPocion(gogoat);
                resultado2 = charizard.atacar(gogoat);
            }
            jTextArea1.append(entrenador + ">>>  " + resultado + "\n" );
            jTextArea1.append(p1.getNombre() + ">>>  " +resultado2 + "\n\n");

            jLabel17.setText(gogoat.MostrarEstado());
            
            
            cant1 = cant1 -1;
            String n1 = cant1 + "";
            jLabel19.setText("Cant. Poción: " +n1);
            if (cant1==0){
                jButton3.setEnabled(false);
            }
            }
        
        if (jFPokemon.jRadioButton3.isSelected()){

            gogoat.setDano((int)(Math.random()*7+5));

            gogoat.setEvasion(20);
            gogoat.setProbabilidad(20);
            gogoat.setCritico(3);
            
            String resultado = "";
            String resultado2 = "";
           
            if(cant1>0){
                resultado = frogadier.usarPocion(frogadier);
                resultado2 = gogoat.atacar(frogadier);
            }
            jTextArea1.append(entrenador + ">>>  " + resultado + "\n" );
            jTextArea1.append(p1.getNombre() + ">>>  " +resultado2 + "\n\n");

            jLabel17.setText(frogadier.MostrarEstado());
            
            
            cant1 = cant1 -1;
            String n1 = cant1 + "";
            jLabel19.setText("Cant. Poción: " +n1);
            if (cant1==0){
                jButton3.setEnabled(false);
            }
            }
        
        
        //Actualizar Estado------
        ////------------------------------------------------
        if (jFPokemon.jRadioButton1.isSelected()){
            jLabel17.setText(charizard.MostrarEstado());
            jLabel18.setText(frogadier.MostrarEstado());

            String cad1 = "Cant. Poción: " +frogadier.getCantPocion() + "";
            jLabel20.setText(cad1);
        }
        if (jFPokemon.jRadioButton2.isSelected()){
            jLabel17.setText(gogoat.MostrarEstado());
            jLabel18.setText(charizard.MostrarEstado());

            String cad1 = "Cant. Poción: " +gogoat.getCantPocion() + "";
            jLabel20.setText(cad1);
        }
        
        if (jFPokemon.jRadioButton3.isSelected()){
            jLabel17.setText(frogadier.MostrarEstado());
            jLabel18.setText(gogoat.MostrarEstado());

            String cad1 = "Cant. Poción: " +frogadier.getCantPocion() + "";
            jLabel20.setText(cad1);
        }
        analizarEstado();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String botones[]={"Rendirse ","Cancelar"};
        int rendirse = JOptionPane.showOptionDialog(this, "¿Desea rendirse ahora?", "¿Rendirse?", 0, 0, null, botones, this);
        if(rendirse==JOptionPane.YES_OPTION){
        
            if(jFPokemon.jRadioButton1.isSelected()){
                jTextArea1.append(entrenador + " se rindió con su Pokemon " + charizard.getNombre() + "  y el ganador \nes " +
                        p1.getNombre() + " con su Pokemon " + frogadier.getNombre());

                jButton1.setEnabled(false);
                jButton3.setEnabled(false);
                jButton4.setEnabled(false);
            }
            if(jFPokemon.jRadioButton2.isSelected()){
                jTextArea1.append(entrenador + " se rindió con su Pokemon " + gogoat.getNombre() + "  y el ganador \nes " +
                        p1.getNombre() + " con su Pokemon " + charizard.getNombre());

                jButton1.setEnabled(false);
                jButton3.setEnabled(false);
                jButton4.setEnabled(false);
            }
            if(jFPokemon.jRadioButton3.isSelected()){
                jTextArea1.append(entrenador + " se rindió con su Pokemon " + frogadier.getNombre() + "  y el ganador \nes " +
                        p1.getNombre() + " con su Pokemon " + gogoat.getNombre());

                jButton1.setEnabled(false);
                jButton3.setEnabled(false);
                jButton4.setEnabled(false);
            }
        }
        else if (rendirse==JOptionPane.NO_OPTION){
            
        }
            
    }//GEN-LAST:event_jButton4ActionPerformed

    
    /**
    
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFBatalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFBatalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFBatalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFBatalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFBatalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
